root = "."
testdata_dir = "testdata"

[build]
cmd = "go build -o ./tmp/bin/main.exe ./main.go"
bin = "./tmp/bin/main.exe"
delay = 100
exclude_dir = ["node_modules"]
include_ext = ["go"]
stop_on_error = false

[misc]
clean_on_exit = true